ToDoList/Controllers/CategoriesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ToDoList.Business.Enums;
using ToDoList.ViewModels.Categories;

namespace ToDoList.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryRepository categoryRepository;
        private readonly IMapper mapper;

        public CategoriesController(IEnumerable<ICategoryRepository> categoryRepositories, IMapper mapper, IHttpContextAccessor httpContextAccessor)
        {
            string? dataProvider = httpContextAccessor.HttpContext.Request.Cookies["DataProvider"];
            categoryRepository = categoryRepositories.GetPropered(dataProvider);
            this.mapper = mapper;
        }

        // GET: CategoriesController
        public async Task<IActionResult> Index(string? like, CategoriesSortOrder sortOrder)
        {
            var categories = await categoryRepository.GetAsync(like, sortOrder);
            return View(mapper.Map<IEnumerable<CategoriesIndexViewModel>>(categories));
        }

        // GET: CategoriesController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            CategoryModel category = await categoryRepository.GetByIdWithTodosOrDefaultAsync(id);
            if(category == null)
                return View(nameof(NotFound));

            return View(mapper.Map<CategoriesDetailsViewModel>(category));
        }

        // GET: CategoriesController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CategoriesController/Create
        [HttpPost]
        public async Task<IActionResult> Create(CategoriesCreateViewModel categoriesCreateViewModel)
        {
            if (!ModelState.IsValid)
                return View(categoriesCreateViewModel);

            CategoryModel category = mapper.Map<CategoryModel>(categoriesCreateViewModel);
            await categoryRepository.CreateAsync(category);
            return RedirectToAction(nameof(Index));
        }

        // GET: CategoriesController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            CategoryModel category = await categoryRepository.GetByIdOrDefaultAsync(id);
            if (category == null)
                return View(nameof(NotFound));

            return View(mapper.Map<CategoriesEditViewModel>(category));
        }

        // POST: CategoriesController/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(CategoriesEditViewModel categoriesEditViewModel)
        {
            if (!ModelState.IsValid)
                return View(categoriesEditViewModel);

            try
            {
                CategoryModel category = mapper.Map<CategoryModel>(categoriesEditViewModel);
                await categoryRepository.UpdateAsync(category);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(categoriesEditViewModel);
            }
        }

        // GET: CategoriesController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            CategoryModel category = await categoryRepository.GetByIdOrDefaultAsync(id);
            if (category == null)
                return View(nameof(NotFound));

            return View(mapper.Map<CategoriesDeleteViewModel>(category));
        }

        // POST: CategoriesController/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            CategoryModel category = await categoryRepository.GetByIdOrDefaultAsync(id);
            if (category == null)
                return View(nameof(NotFound));

            await categoryRepository.RemoveAsync(category.Id);
            return RedirectToAction(nameof(Index));
        }

        // GET: CategoriesController/NotFound
        public IActionResult NotFound()
        {
            return View();
        }
    }
}

ToDoList/Controllers/ToDosController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ToDoList.Business.Enums;
using ToDoList.ViewModels.ToDos;
using static ToDoList.ViewModels.ToDos.ToDosIndexViewModel;

namespace ToDoList.Controllers
{
    public class ToDosController : Controller
    {
        private readonly IToDoRepository toDoRepository;
        private readonly ICategoryRepository categoryRepository;
        private readonly IMapper mapper;

        public ToDosController(IEnumerable<IToDoRepository> toDoRepositories, IEnumerable<ICategoryRepository> categoryRepositories, IMapper mapper, IHttpContextAccessor httpContextAccessor)
        {
            string? dataProvider = httpContextAccessor.HttpContext.Request.Cookies["DataProvider"];
            toDoRepository = toDoRepositories.GetPropered(dataProvider);
            categoryRepository = categoryRepositories.GetPropered(dataProvider);
            this.mapper = mapper;
        }

        // GET: ToDosController
        public async Task<IActionResult> Index(string? like, ToDosSortOrder sortOrder, int? categoryId)
        {
            var toDos = await toDoRepository.GetWithCategoryAsync(like, sortOrder, categoryId);
            var categories = await categoryRepository.GetAsync(string.Empty, CategoriesSortOrder.NameAsc);
            ToDosIndexViewModel toDosIndexViewModel = new ToDosIndexViewModel
            {
                ToDos = mapper.Map<List<ToDoIndexViewModel>>(toDos),
                Categories = categories
            };
            return View(toDosIndexViewModel);
        }

        // GET: ToDosController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            ToDoModel toDo = await toDoRepository.GetByIdOrDefaultAsync(id);
            if (toDo == null)
                return View(nameof(NotFound));

            return View(mapper.Map<ToDosDetailsViewModel>(toDo));
        }

        // POST: ToDosController/Create
        [HttpPost]
        public async Task<IActionResult> Create(ToDosCreateViewModel toDosCreateViewModel)
        {
            if (!ModelState.IsValid)
            {
                var toDos = await toDoRepository.GetWithCategoryAsync(like: null, ToDosSortOrder.DeadlineAcs, categoryId: null);
                var categories = await categoryRepository.GetAsync(like: string.Empty, CategoriesSortOrder.NameAsc);
                ToDosIndexViewModel toDosIndexViewModel = new ToDosIndexViewModel
                {
                    CreateToDo = toDosCreateViewModel,
                    ToDos = mapper.Map<List<ToDoIndexViewModel>>(toDos),
                    Categories = categories
                };
                return View(nameof(Index), toDosIndexViewModel);
            }
            ToDoModel toDo = mapper.Map<ToDoModel>(toDosCreateViewModel);
            await toDoRepository.CreateAsync(toDo);
            return RedirectToAction(nameof(Index));
        }

        // GET: ToDosController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            ToDoModel toDo = await toDoRepository.GetByIdOrDefaultAsync(id);
            if (toDo == null)
                return View(nameof(NotFound));
            ToDosEditViewModel toDosEditViewModel = new ToDosEditViewModel();
            toDosEditViewModel.ToDo = mapper.Map<ToDoEditViewModel>(toDo);
            toDosEditViewModel.Categories = await categoryRepository.GetAsync(string.Empty, CategoriesSortOrder.DateDesc);
            return View(toDosEditViewModel);
        }

        // POST: ToDosController/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(ToDoEditViewModel toDoEditViewModel)
        {
            ToDosEditViewModel toDosEditViewModel = new ToDosEditViewModel();
            toDosEditViewModel.ToDo = toDoEditViewModel;
            toDosEditViewModel.Categories = await categoryRepository.GetAsync(string.Empty, CategoriesSortOrder.DateDesc);

            if (!ModelState.IsValid)
                return View(toDosEditViewModel);

            try
            {
                ToDoModel toDo = mapper.Map<ToDoModel>(toDoEditViewModel);
                await toDoRepository.UpdateAsync(toDo);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(toDosEditViewModel);
            }
        }

        // GET: ToDosController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            ToDoModel toDo = await toDoRepository.GetByIdOrDefaultAsync(id);
            if (toDo == null)
                return View(nameof(NotFound));

            return View(mapper.Map<ToDosDeleteViewModel>(toDo));
        }

        // POST: ToDosController/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ToDoModel toDo = await toDoRepository.GetByIdOrDefaultAsync(id);
            if (toDo == null)
                return View(nameof(NotFound));

            await toDoRepository.RemoveAsync(toDo.Id);
            return RedirectToAction(nameof(Index));
        }

        // POST: ToDosController/SwitchIsDone?id=5&isDone=true
        [HttpPost]
        public async Task<IActionResult> SwitchIsComplete(int id, bool isComplete)
        {
            ToDoModel toDo = await toDoRepository.GetByIdOrDefaultAsync(id);
            if (toDo == null)
                return View(nameof(NotFound));

            toDo.IsComplete = isComplete;
            await toDoRepository.UpdateAsync(toDo);
            return Ok(toDo);
        }

        // GET: ToDosController/NotFound
        public IActionResult NotFound()
        {
            return View();
        }
    }
}

ToDoList/Views/Shared/NotFound.cshtml
@{
    string message = "Not Found";
    ViewData["Title"] = message;
}

<div class="alert alert-danger">
    @message
</div>

ToDoList/Views/Shared/_Layout.cshtml
@using ToDoList.Enums

@{
    string currentDataProvider = ViewContext.HttpContext.Request.Cookies["DataProvider"];
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoList.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="" asp-action="">ToDoList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDos" asp-action="Index">ToDos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <form>
                            <select name="dataProvider" id="dataProvider" class="form-control">
                                @foreach (var dataProvider in Enum.GetNames(typeof(DataProvider)))
                                {
                                    <option selected=@((bool)(currentDataProvider == dataProvider)) value="@dataProvider">@dataProvider.SplitCamelCase()</option>
                                }
                            </select>
                        </form>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationPartial" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ToDoList
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoList/Views/Shared/_NotificationPartial.cshtml
@if (TempData["Success"] != null)
{
    <div class="alert alert-success notification">
        @TempData["Success"]
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger notification">
        @TempData["Error"]
    </div>
}